### ISSUE TITLE
turn off  -log10 in manhattan plot

### ISSUE THREAD

**Issue by ArashBayat** [khramts/assocplots#1]
Would you please add an option to turn off -log10 when doing manhattan plot.

**Comment by khramts** [comment]
I have modified the code to allow turning off -log10. When the scaling option is set to 'none', the -log10 will not be applied. Otherwise, the scaling should be set to '-log10'. 
Example from the tutorial: 
manhattan(     hip_m['f3'], hip_m['f1'], hip_m['f0'].astype(str), 'Hip men',
               type='single',
               chrs_plot=[str(i) for i in range(1,23)],
               chrs_names=chrs_names,
               cut = 0,
               title='Anthropometric traits',
               xlabel='chromosome',
               ylabel='-log10(p-value)',
               lines= [],
               colors = colors,
               scaling = 'none')

**Comment by ArashBayat** [comment]
Really appreciate it
